### ISSUE TITLE
error parsing lifetime

### ISSUE THREAD

**Issue by wagnerf42** [rust-lang-nursery/rustfmt#1617]
the following code compiles and runs.
however rustfmt complains with the following message
"
error: expected `,` or `>` after lifetime name, found `+`
 --> src/main.rs:4:23
  |
4 |     generator: Box<'a + Fn(i32) -> i32>,
  |                       ^
  |
note: did you mean a single argument type &'a Type, or did you mean the comma-separated arguments 'a, Type?
 --> src/main.rs:4:20
  |
4 |     generator: Box<'a + Fn(i32) -> i32>,
  |                    ^^^^
"

`struct Vecky<'a> {
    v: Vec<i32>,
    generator: Box<'a + Fn(i32) -> i32>,
}

impl<'a> Vecky<'a> {
    fn new<F: 'a + Fn(i32) -> i32>(v: Vec<i32>, f: F) -> Vecky<'a> {
        Vecky {
            v,
            generator: Box::new(f),
        }
    }
}

impl<'a> Vecky<'a> {
    fn newbie(v: Vec<i32>) -> Vecky<'a> {
        Vecky {
            v,
            generator: Box::new(|x| x),
        }
    }
    fn print_keys(&self) {
        for x in &self.v {
            println!("{} ", (self.generator)(*x));
        }
    }
}

fn main() {
    let v = Vecky::newbie(vec![1, 2, 3]);
    v.print_keys();
    let v2 = Vecky::new(vec![1,2,3], |x|x+1);
    v2.print_keys();
}
`

**Comment by nrc** [comment]
Could you try the libsyntax branch please? I assume this is fixed there.

**Comment by wagnerf42** [comment]
hi, I get the same error message in the libsyntax branch.

wagnerf@havasupai /t/rustfmt ❯❯❯ git branch                                                                          ⏎
* libsyntax
  master
wagnerf@havasupai /t/rustfmt ❯❯❯ cargo run --bin rustfmt /tmp/foo/src/main.rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/rustfmt /tmp/foo/src/main.rs`
error: expected `,` or `>` after lifetime name, found `+`

**Comment by nrc** [comment]
@wagnerf42 thanks for checking, that is a bit worrying, I'll investigate...

**Comment by nrc** [comment]
I can reproduce on master but not on libsyntax branch. You might need to update to a more recent nightly compiler?

**Comment by wagnerf42** [comment]
That's strange.
I'm still getting the error with the latest version.

wagnerf@havasupai /t/rustfmt ❯❯❯ rustc --version
rustc 1.19.0-nightly (e0cc22b4b 2017-05-31)
wagnerf@havasupai /t/rustfmt ❯❯❯ git branch
* libsyntax
  master
wagnerf@havasupai /t/rustfmt ❯❯❯ cargo run --bin rustfmt /tmp/foo/src/main.rs
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/rustfmt /tmp/foo/src/main.rs`
error: expected `,` or `>` after lifetime name, found `+`

**Comment by nrc** [comment]
Have you pulled the remote branch properly? HEAD should be at 6c1de7694782d9f710b2f00b1f650f266a99b384

**Comment by wagnerf42** [comment]
oh you are right. sorry, i'm not too used to branches and I did not pull after switching.
it's ok with latest libsyntax.

thanks a lot
