### ISSUE TITLE
`array!` macro from ndarray crate failing due to rustfmt adding trailing comma

### ISSUE THREAD

**Issue by Majora320** [rust-lang-nursery/rustfmt#1856]
When I have a macro call to the  [`array!`](https://docs.rs/ndarray/0.10.0/ndarray/macro.array.html) macro from the [ndarray](https://docs.rs/ndarray/0.10.0/ndarray/) crate, say:

    let a = array![
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]
            ]
Rustfmt will add a trailing comma to the last array part, turning it into:

    let a = array![
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16],
            ]
Which results in a syntax error.

Is this fixable in a clean-ish way without too much special casing, or should I ask for a fix upstream to allow an optional trailing comma?

**Comment by nrc** [comment]
Does this reproduce in rustfmt-nightly latest version? And/or master? Because I think we have fixed this bug before.

**Comment by Dushistov** [comment]
I have the same problem:
```sh
$ rustfmt --version
0.9.0-nightly ( )
```
When I use macros from [cpython](https://github.com/dgrunwald/rust-cpython):
```rust
    m.add(py,
             "save_data_as_xml",
             py_fn!(py,
                    save_data_as_xml_py(params: SomeStructName, out_name: &str, addon_param: &str)))?;
```

`rustfmt` format it to:
```rust
    m.add(
        py,
        "save_data_as_xml",
        py_fn!(
            py,
            save_data_as_xml_py(
                params: SomeStructName,
                out_name: &str,
                addon_param: &str,
            )
        ),
    )?;
```

The addon comma after `addon_param: &str` break compilation

**Comment by nrc** [comment]
@Dushistov can you also try with rustfmt-nightly (or master) please?

**Comment by Dushistov** [comment]
@nrc 

I tried rustfmt-nightly (`0.2.1-nightly ( )):
the output little different, but additional comma in the same place, so build still FAILED:

```rust
    m.add(
        py,
        "save_data_as_xml",
        py_fn!(
            py,
            save_data_as_xml_py(params: SomeStructName, out_name: &str, addon_param: &str,)
        ),
    )?;
```

**Comment by Dushistov** [comment]
@nrc 

Wait, I tryied with already modified sources by bad `rustfmt`,
will retry with clean sources

**Comment by Dushistov** [comment]
@nrc 

With clean sources `rustfmt-nightly` (`0.2.1-nightly ( )`) works well: 

```diff
-    m.add(py,
-             "save_data_as_xml",
-             py_fn!(py,
-                    save_data_as_xml_py(params: SomeStructName, out_name: &str, addon_param: &str)))?;
+    m.add(
+        py,
+        "save_data_as_xml",
+        py_fn!(
+            py,
+            save_data_as_xml_py(params: SomeStructName, out_name: &str, addon_param: &str)
+        ),
+    )?;
```

**Comment by Majora320** [comment]
Confirmed fixed in nightly; only thing to do now is to wait for the next release. Closing.
